move both gerrit and redmine to host network

diff --git a/redmine/run b/redmine/run
--- a/redmine/run
+++ b/redmine/run
@@ -5,10 +5,27 @@ set -o nounset
 set -o pipefail
 
 run() {
+    local bindIP="127.0.0.1"
+
+    while [[ $# -gt 0 ]]; do
+        case "$1" in
+            "--bind")
+                shift
+                echo "Using bind IP $1 instead of $bindIP"
+                bindIP="$1"
+                ;;
+            *)
+                echo "Invalid option: $1" >&2
+                exit 1
+                ;;
+        esac
+        shift
+    done
+
     cd "$HOME/redmine"
     cp data/secret_token.rb config/initializers/
     exec bundle exec rails server -e production --log-to-stdout -u puma \
-        -b "0.0.0.0" -p 3000
+        -b "$bindIP" -p 3000
 }
 
 run "$@"
